const DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID!;
const WORKSPACES_ID = process.env.NEXT_PUBLIC_APPWRITE_WORKSPACES_ID!;
const PROJECTS_ID = process.env.NEXT_PUBLOC_APPWRITE_RPOJECTS_ID!;
const TASKS_ID = process.env.NEXT_PUBLOC_APPWRITE_TASKS_ID!;
const IMAGES_BUCKET_ID = process.env.NEXT_PUBLIC_APPWRITE_IMAGE_BUCKET_ID!;
const MEMBERS_ID = process.env.NEXT_PUBLOC_APPWRITE_MEMBERS_ID!;

export {
  DATABASE_ID,
  WORKSPACES_ID,
  MEMBERS_ID,
  PROJECTS_ID,
  TASKS_ID,
  IMAGES_BUCKET_ID,
};
