import type { Metadata } from "next";
import { Inter } from "next/font/google";

import NuqsProvider from "@/components/partials/providers/nuqs-provider";
import QueryProvider from "@/components/partials/providers/query-provider";
import ToastProvider from "@/components/partials/providers/toast-provider";
import { cn } from "@/lib/utils";

import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "antialiased min-h-screen")}>
        <QueryProvider>
          <NuqsProvider>
            <ToastProvider />
            {children}
          </NuqsProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
